### PR TITLE
Added XML docs to methods that can throw custom exceptions so that ca…

### PR DESCRIPTION
**Pull request by ronwarner**
…llers will know which exceptions to expect.  There are a couple other minor things thrown in, too.

### CODE REVIEW

**Comment by ronwarner** [comment]
Hi!  I was writing something that uses this library, and found myself constantly checking the source to see what exceptions I should plan for.  I thought documenting the possible custom exceptions thrown from each method might help consumers (myself included) better prepare their consuming code.  I thought I should mention, I couldn't get some of the unit tests to pass, but I assume that has more to do with problems from trying to authenticate with my own account, supplying 2FA codes, etc.

**Comment by KoenZomers** [comment]
Thanks a lot for your nice contribution @ronwarner! I've merged it through PR #14 .

**Comment by ronwarner** [comment]
Thanks for providing a helpful library, @KoenZomers!  By the way, I was curious if you use editor configs, analyzers, ReSharper, or anything like that?  I didn't notice any files for configuring such things in the repo, and wondered if I'd accidentally step on your style.

**Comment by KoenZomers** [comment]
Not using any tools to aid in that. I believe I removed some extra spaces before merging, but that was about it that would differentiate from the style I apply. So all good.

**Comment by KoenZomers** [comment]
I'm still working on rewriting the Unit Tests to make them work better with the two factor authentication by the way. Will be coming soon.

**Comment by KoenZomers** [comment]
Unit Test has been updated to work better with two factor authentication now. Also released a new NuGet package with the changes of this PR included.

**Pull request merged**
